// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nudwtdzwcjfvvxpubbdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZHd0ZHp3Y2pmdnZ4cHViYmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzgwOTMsImV4cCI6MjA3MDcxNDA5M30.PhYHF1NON9aclBX73uiiw5yA-iJn3Et8og_sd6BM-VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});